version: "2"
services:
  node:
    image: "nodeservice/backend"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - 8000:8000
